version: '3'

vars:
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo dev
  BINARY: specmcp
  OUTDIR: dist

tasks:
  default:
    desc: Build the binary
    aliases: [build]
    cmds:
      - mkdir -p {{.OUTDIR}}
      - echo "Building {{.BINARY}} {{.VERSION}}..."
      - go build -ldflags "-X main.Version={{.VERSION}}" -o {{.OUTDIR}}/{{.BINARY}} ./cmd/specmcp/
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
    generates:
      - "{{.OUTDIR}}/{{.BINARY}}"

  run:
    desc: Build and run the binary
    deps: [build]
    cmds:
      - "{{.OUTDIR}}/{{.BINARY}}"

  install:
    desc: Install the binary via go install
    cmds:
      - go install -ldflags "-X main.Version={{.VERSION}}" ./cmd/specmcp/

  test:
    desc: Run tests
    cmds:
      - go test ./...

  seed:
    desc: Register template pack with Emergent
    cmds:
      - echo "Seeding template pack..."
      - go run ./scripts/seed.go

  fmt:
    desc: Format Go source files
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  tidy:
    desc: Tidy Go module dependencies
    cmds:
      - go mod tidy

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.OUTDIR}}

  docker:
    desc: Build Docker image with BuildKit caching
    cmds:
      - DOCKER_BUILDKIT=1 docker build --build-arg BUILDKIT_INLINE_CACHE=1 -t specmcp .

  build-all:
    desc: Build for all platforms (release)
    cmds:
      - task: build-darwin-arm64
      - task: build-darwin-amd64
      - task: build-linux-amd64
      - task: build-linux-arm64

  build-darwin-arm64:
    desc: Build for macOS ARM64
    cmds:
      - mkdir -p {{.OUTDIR}}
      - echo "Building {{.BINARY}} {{.VERSION}} for darwin/arm64..."
      - GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w -X main.Version={{.VERSION}}" -o {{.OUTDIR}}/{{.BINARY}}-darwin-arm64 ./cmd/specmcp/

  build-darwin-amd64:
    desc: Build for macOS Intel
    cmds:
      - mkdir -p {{.OUTDIR}}
      - echo "Building {{.BINARY}} {{.VERSION}} for darwin/amd64..."
      - GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w -X main.Version={{.VERSION}}" -o {{.OUTDIR}}/{{.BINARY}}-darwin-amd64 ./cmd/specmcp/

  build-linux-amd64:
    desc: Build for Linux x86_64
    cmds:
      - mkdir -p {{.OUTDIR}}
      - echo "Building {{.BINARY}} {{.VERSION}} for linux/amd64..."
      - GOOS=linux GOARCH=amd64 go build -ldflags "-s -w -X main.Version={{.VERSION}}" -o {{.OUTDIR}}/{{.BINARY}}-linux-amd64 ./cmd/specmcp/

  build-linux-arm64:
    desc: Build for Linux ARM64
    cmds:
      - mkdir -p {{.OUTDIR}}
      - echo "Building {{.BINARY}} {{.VERSION}} for linux/arm64..."
      - GOOS=linux GOARCH=arm64 go build -ldflags "-s -w -X main.Version={{.VERSION}}" -o {{.OUTDIR}}/{{.BINARY}}-linux-arm64 ./cmd/specmcp/

  release:
    desc: Create release archives for all platforms
    deps: [build-all]
    cmds:
      - echo "Creating release archives..."
      - |
        cd {{.OUTDIR}}
        for f in {{.BINARY}}-*; do
          [ -f "$f" ] || continue
          tar -czvf ${f}.tar.gz ${f}
          sha256sum ${f}.tar.gz > ${f}.tar.gz.sha256
        done
        cat *.sha256 > checksums.txt
      - echo "Release archives created in {{.OUTDIR}}/"
      - ls -lh {{.OUTDIR}}/*.tar.gz

  build-arch:
    desc: Build Arch Linux package
    cmds:
      - echo "Building Arch Linux package..."
      - cd pkg/arch && makepkg -f

